graph TD
    SZ --- GQ & YZ
    SP --- LJ & AA
    LQ --- EY & JT
    AT --- DX & BU & NE & BR & TD
    IR --- XN & UI
    CF --- XN & BR
    TE --- YA & RY
    GQ --- SZ & AQ & OW & XJ
    DX --- HI & AT
    AQ --- AZ & GQ
    NE --- AT & IA
    OC --- PE & QV & QI & LJ & WX
    JO --- AA & UI
    BR --- CF & AT
    ZW --- JH & EY
    TD --- AT & WX
    BU --- AT & ES
    QI --- OC & XN
    PE --- CI & OC
    WX --- TD & OC
    IA --- UI & NE
    TR --- HI
    JK --- QV & UI
    UB --- OM & AA
    KW --- YL & MD
    AL --- ZL & WZ
    VK --- OM & ZL & CI & VA & XJ
    FF --- VD & AA
    MD --- KW & YA
    VA --- AZ & VK
    CI --- VK & PE
    LJ --- SP & OC
    YL --- OW & KW
    JH --- RK & ZW
    ES --- BU
    OM --- UB & VK
    QV --- OC & JK
    XN --- QI & VD & IR & CF & OG
    EY --- ZW & LQ & XC & RC
    XJ --- GQ & VK
    HI --- DX & TR
    VD --- FF & XN
    RY --- AZ & TE
    YZ --- SZ & YA
    YA --- YZ & MD & TE
    AZ --- AQ & RC & RY & VA
    ZL --- AL & VK
    UE --- RK & UI
    WZ --- AL
    EB --- AA & XC
    UI --- UE & JK & IR & JO & IA
    AA --- UB & JO & FF & EB & SP
    OG --- XN & DF
    RC --- AZ & EY
    JT --- LQ
    DF --- OG & RK
    RK --- DF & JH & UE
    OW --- YL & GQ
    XC --- EY & EB
